### ISSUE TITLE
`t` GET variable isn't triggering the automatic click

### ISSUE THREAD

**Issue by FlipperPA** [wharton/wagtailgridder#16]
This code isn't being included in the template:

https://github.com/wharton/wagtailgridder/blob/main/wagtailgridder/templates/wagtailgridder/index/__wg-content-container.html#L147

See the WRDS Classroom page for an example.

**Comment by noeldvictor** [comment]
https://github.com/wharton/wagtailgridder/blob/main/wagtailgridder/templates/wagtailgridder/grid_index_page.html#L27
The usage of the cache template tag is causing the error.
This is because request.path in the template doesn't include url parameters, so that block needs to be request.get_full_path.
I'll have a fix tomorrow (2023.05.17).

**Comment by FlipperPA** [comment]
@noeldvictor Awesome, thanks a bundle. I figured it was something with caching, but was completely worn out. 👍

**Comment by noeldvictor** [comment]
After looking into this in depth, the easy/fast fix works, but then we have a cache page fragment for every url parameter as well..
I'm going to spend some more time on this, to pull the javascript code outside the cached fragments.

**Comment by FlipperPA** [comment]
Sounds good, thanks @noeldvictor.

**Comment by FlipperPA** [comment]
Thanks @noeldvictor!
